# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8002
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

dubbo:
  application:
    name: job
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    loadbalance: roundrobin
    check: false
    timeout: 30000

# 日志配置
logging:
  level:
    com.carebed: debug
    org.springframework: warn
